addons:
  apt:
    packages:
    - gmake
language: cpp
env:
  - PREFIX="$TRAVIS_BUILD_DIR/test-1.1.10" GDAL_VERSION="1.1.10" FILEGDB_API_PATH="Invalid-filegdb-api-path"
  - PREFIX="$TRAVIS_BUILD_DIR/test-2.0.0" GDAL_VERSION="2.0.0" FILEGDB_API_PATH="Invalid-filegdb-api-path"
script: install-scripts/gdal-install.sh && $PREFIX/init-gdal.sh && ogrinfo --formats
